### PR TITLE
New option cache

### PR DESCRIPTION
**Pull request by ricardofbarros**
Following #2.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
can you use `test/fixtures` for running test fixtures (instead of `tmp`) 

thanks

**Comment by ricardofbarros** [comment]
done :)

**Comment by ahmadnassri** [comment]
thank you :)

**Comment by ricardofbarros** [comment]
Please don't forget to do a version bump and publish the package.

**Comment by ahmadnassri** [comment]
yep

**Comment by ahmadnassri** [comment]
released in `v1.1.0`

**Pull request merged**
